### ISSUE TITLE
Login Loading Error

### ISSUE THREAD

**Issue by Klevi7** [haxxorsid/food-ordering-system#1]
Hello when I log in with admin/costumer credentials it stays loading/buffering all the time. Database is configured correctly and registering new users works well, but login doesn't work. Why does it happen?

**Comment by haxxorsid** [comment]
It is working fine on my setup. Check for logs or any warnings.

**Comment by Klevi7** [comment]
I cleared logs, caches etc both on chrome and mozilla but it just keeps buffering. Can you help me please?

**Comment by Klevi7** [comment]
The problem is at buffering effect. When I remove after as I log in as admin, I can see the admin view. When I click at Users it works, but it doesn't work when I click at orders or tickets.

**Comment by haxxorsid** [comment]
If by buffering effect you mean the splash screen(colorful loading circle) then you can try removing it from webpages:
This is the code which is present in all .php files in the root-
```
  <div id="loader-wrapper">
      <div id="loader"></div>        
      <div class="loader-section section-left"></div>
      <div class="loader-section section-right"></div>
  </div>
```
This might be a problem because of JS/CSS/Browser.
If this doesn't fix it then it might problem with your development environment(maybe too slow) or code doesn't support your environment or there is some real problem with code. 

> My environment:  PHP5.6 (on XAMPP)

If this doesn't fix it, then you will have to provide me some typical error message your system is giving you, else I won't be able to solve your problem.

**Comment by Klevi7** [comment]
My browser says that the problem seems to be that custom.min.css is not loading. I use phpstorm 9.0 and xampp. I removed all the loading circle codes. 
Problems that I face is that in admin page orders/tickets can not be clicked. When I login as a user I can only see the amount of dollars in the right top and that's all nothing is showed.

**Comment by haxxorsid** [comment]
`custom.min.css `is blank. So that should not matter.
Other than that please check if your PHP supports the code. I have doubt if PHP7 supports it. 
Regarding your problem: I need the proper error, warning your system is generating else I can't help you.

**Comment by Klevi7** [comment]
I just tried it with php 5.6 and it still doesn't work properly. You don't have any bugs in your project? All the functionalities are working?

**Comment by haxxorsid** [comment]
All the functionalities are working on my environment. Try it on your alternative or any colleague's PC. I have added some screenshots in `README.md` if you want to take a look.

**Comment by haxxorsid** [comment]
I am closing this issue since there was no followup on this. Thanks.
